name: Testing pycasm

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          cache: "pip"
      - name: Install depenedencies
        run: |
          pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Run tests
        run: pytest --exitfirst --verbose --failed-first
